name       : python-watchdog
version    : 0.8.3
release    : 1
source     :
    - https://github.com/gorakhargosh/watchdog/archive/v0.8.3.tar.gz : e9a27d0ab121fc86217ab833e778c76880aad4ecdb623796f4b7aee9925394ed
license    : Apache-2.0
component  : programming.python
summary    : Python library and shell utilities to monitor filesystem events.
description: |
    Python library and shell utilities to monitor filesystem events.
builddeps  :
    - python-pathtools
    - python-setuptools
rundeps    :
    - python-pathtools
build      : |
    %python_setup    
install    : |
    %python_install
