name       : python-watchdog
version    : 2.1.8
release    : 11
source     :
    - https://github.com/gorakhargosh/watchdog/archive/refs/tags/v2.1.8.tar.gz : b7e25a754756fab696ea06021ea0aba9699d5ac5178420c64f20cddd1f272baf
homepage   : https://github.com/gorakhargosh/watchdog
license    : Apache-2.0
component  : programming.python
summary    : Python library and shell utilities to monitor filesystem events
description: |
    Python library and shell utilities to monitor filesystem events.
builddeps  :
    - python-pytest-cov
    - python-pytest-timeout
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 \
        --deselect tests/test_inotify_buffer.py::test_unmount_watched_directory_filesystem
