name       : python-watchdog
version    : 0.10.3
release    : 7
source     :
    - https://github.com/gorakhargosh/watchdog/archive/v0.10.3.tar.gz : f7e5040b483cc9a8618a4e72c11a527b42434a0766ea96dce633e8b44b1369de
homepage   : https://github.com/gorakhargosh/watchdog
license    : Apache-2.0
component  : programming.python
summary    : Python library and shell utilities to monitor filesystem events
description: |
    Python library and shell utilities to monitor filesystem events.
builddeps  :
    - python-argh
    - python-pathtools
    - python-pytest-cov
    - python-pytest-timeout
rundeps    :
    - python-argh
    - python-pathtools
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
