name       : python-watchdog
version    : 2.1.9
release    : 12
source     :
    - https://github.com/gorakhargosh/watchdog/archive/refs/tags/v2.1.9.tar.gz : 543118818ba427445b129ce57af2e38f439045a6fe87bb944fca44b48f693202
homepage   : https://github.com/gorakhargosh/watchdog
license    : Apache-2.0
component  : programming.python
summary    : Python library and shell utilities to monitor filesystem events
description: |
    Python library and shell utilities to monitor filesystem events.
builddeps  :
    - python-pytest-cov
    - python-pytest-timeout
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 \
        --deselect tests/test_inotify_buffer.py::test_unmount_watched_directory_filesystem
