name       : python-watchdog
version    : 2.1.6
release    : 8
source     :
    - https://github.com/gorakhargosh/watchdog/archive/refs/tags/v2.1.6.tar.gz : da8acc2510e532260553c21b7235a8a14c4d5279b8564c5552f9b3433621b2b5
homepage   : https://github.com/gorakhargosh/watchdog
license    : Apache-2.0
component  : programming.python
summary    : Python library and shell utilities to monitor filesystem events
description: |
    Python library and shell utilities to monitor filesystem events.
builddeps  :
    - python-argh
    - python-pathtools
    - python-pytest-cov
    - python-pytest-timeout
rundeps    :
    - python-argh
    - python-pathtools
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
