name       : python-watchdog
version    : 0.9.0
release    : 4
source     :
    - https://github.com/gorakhargosh/watchdog/archive/v0.9.0.tar.gz : e8a32701dff43a4e671a40acf92f55a8fffd8ca74333b75436d63a94d104faef
license    : Apache-2.0
component  : programming.python
summary    : Python library and shell utilities to monitor filesystem events.
description: |
    Python library and shell utilities to monitor filesystem events.
builddeps  :
    - pkgconfig(python3)
    - python-pathtools
    - python-setuptools
rundeps    :
    - python-argh
    - python-pathtools
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    needs pytest-timeout packaged
#    %python3_test pytest3
