name       : python-watchdog
version    : 2.2.1
release    : 13
source     :
    - https://github.com/gorakhargosh/watchdog/archive/refs/tags/v2.2.1.tar.gz : c5d0ca28c1ff7ba49ff2efb44bf59a895ebcfd860f03a6404079bb37dc257685
homepage   : https://github.com/gorakhargosh/watchdog
license    : Apache-2.0
component  : programming.python
summary    : Python library and shell utilities to monitor filesystem events
description: |
    Python library and shell utilities to monitor filesystem events.
builddeps  :
    - python-pytest-cov
    - python-pytest-timeout
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 \
        --deselect tests/test_inotify_buffer.py::test_unmount_watched_directory_filesystem
