name       : python-watchdog
version    : 2.1.7
release    : 10
source     :
    - https://github.com/gorakhargosh/watchdog/archive/refs/tags/v2.1.7.tar.gz : 1fc4abc666f9e7a4127b06ff9aa940fa782497ec656460b9af31e21cf610bc6f
homepage   : https://github.com/gorakhargosh/watchdog
license    : Apache-2.0
component  : programming.python
summary    : Python library and shell utilities to monitor filesystem events
description: |
    Python library and shell utilities to monitor filesystem events.
builddeps  :
    - python-argh
    - python-pathtools
    - python-pytest-cov
    - python-pytest-timeout
rundeps    :
    - python-argh
    - python-pathtools
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
